name: chrono

services:
  postgres:
    image: postgres
    container_name: chrono-postgres
    environment:
      POSTGRES_DB: chrono
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - chrono_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  chrono_postgres_data:
